"""adicionando fk de seller_id a entidade curso

Revision ID: 5b2dc9be9ee6
Revises: b2b2d068b647
Create Date: 2025-01-26 21:59:57.222965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2dc9be9ee6'
down_revision: Union[str, None] = 'b2b2d068b647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'courses', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'seller_id')
    # ### end Alembic commands ###
