"""criação automática das tabelas solucionada

Revision ID: 7d15c6125b77
Revises: efd1122bd169
Create Date: 2025-01-21 17:31:50.453745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d15c6125b77'
down_revision: Union[str, None] = 'efd1122bd169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
