"""adicionando campo phone number a entidade curso

Revision ID: e3ddd561ed1a
Revises: 5b2dc9be9ee6
Create Date: 2025-01-26 23:28:35.926832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3ddd561ed1a'
down_revision: Union[str, None] = '5b2dc9be9ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'phone_number')
    # ### end Alembic commands ###
